//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasType.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasType.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add New....
        /// </summary>
        public static string AddNewHeader {
            get {
                return ResourceManager.GetString("AddNewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Abbreviations.
        /// </summary>
        public static string AllAbbrevs {
            get {
                return ResourceManager.GetString("AllAbbrevs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The abbreviation you are trying to create already exists.{0}({1}).
        /// </summary>
        public static string AlreadyExistsErrorFormat {
            get {
                return ResourceManager.GetString("AlreadyExistsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FasType.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this abbreviation?{0}({1}).
        /// </summary>
        public static string DeleteDialogFormat {
            get {
                return ResourceManager.GetString("DeleteDialogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t create an empty abbreviation..
        /// </summary>
        public static string EmptyAbbrevDialog {
            get {
                return ResourceManager.GetString("EmptyAbbrevDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while trying to create the abbreviation.{0}({1}).
        /// </summary>
        public static string ErrorDialogFormat {
            get {
                return ResourceManager.GetString("ErrorDialogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Form.
        /// </summary>
        public static string FullForm {
            get {
                return ResourceManager.GetString("FullForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistics.
        /// </summary>
        public static string Linguistics {
            get {
                return ResourceManager.GetString("Linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Linguistics.
        /// </summary>
        public static string LinguisticsHeader {
            get {
                return ResourceManager.GetString("LinguisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix.
        /// </summary>
        public static string Postfix {
            get {
                return ResourceManager.GetString("Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run At Start Up.
        /// </summary>
        public static string RunAtStartUp {
            get {
                return ResourceManager.GetString("RunAtStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _See All.
        /// </summary>
        public static string SeeAllHeader {
            get {
                return ResourceManager.GetString("SeeAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Form.
        /// </summary>
        public static string ShortForm {
            get {
                return ResourceManager.GetString("ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Simple Abbrev..
        /// </summary>
        public static string SimpleAbbrevHeader {
            get {
                return ResourceManager.GetString("SimpleAbbrevHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Simple Abbreviation.
        /// </summary>
        public static string SimpleAbbrevTitle {
            get {
                return ResourceManager.GetString("SimpleAbbrevTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Verb Abbrev..
        /// </summary>
        public static string VerbAbbrevHeader {
            get {
                return ResourceManager.GetString("VerbAbbrevHeader", resourceCulture);
            }
        }
    }
}
