//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasType.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FasType.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation Auto-Creation.
        /// </summary>
        public static string AbbrevAutoCreation {
            get {
                return ResourceManager.GetString("AbbrevAutoCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation Method.
        /// </summary>
        public static string AbbreviationMethod {
            get {
                return ResourceManager.GetString("AbbreviationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviations auto-creation.
        /// </summary>
        public static string AbbrevsAutoCreation {
            get {
                return ResourceManager.GetString("AbbrevsAutoCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add New....
        /// </summary>
        public static string AddNewHeader {
            get {
                return ResourceManager.GetString("AddNewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Simple Abbreviation.
        /// </summary>
        public static string AddSimpleAbbrevTitle {
            get {
                return ResourceManager.GetString("AddSimpleAbbrevTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Abbreviations.
        /// </summary>
        public static string AllAbbrevs {
            get {
                return ResourceManager.GetString("AllAbbrevs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FasType.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-complete.
        /// </summary>
        public static string AutoComplete {
            get {
                return ResourceManager.GetString("AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Completion.
        /// </summary>
        public static string DefaultCompletion {
            get {
                return ResourceManager.GetString("DefaultCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such abbreviation already exists..
        /// </summary>
        public static string DupAbbrevToolTip {
            get {
                return ResourceManager.GetString("DupAbbrevToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any.
        /// </summary>
        public static string EmptyAbbrevMethodList1 {
            get {
                return ResourceManager.GetString("EmptyAbbrevMethodList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation Methods registered.
        /// </summary>
        public static string EmptyAbbrevMethodList2 {
            get {
                return ResourceManager.GetString("EmptyAbbrevMethodList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an empty abbreviation..
        /// </summary>
        public static string EmptyAbbrevToolTip {
            get {
                return ResourceManager.GetString("EmptyAbbrevToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any One-Letters abbreviations..
        /// </summary>
        public static string EmptyOneLetters1 {
            get {
                return ResourceManager.GetString("EmptyOneLetters1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is highly recommended to use them as much as possible..
        /// </summary>
        public static string EmptyOneLetters2 {
            get {
                return ResourceManager.GetString("EmptyOneLetters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Form.
        /// </summary>
        public static string FullForm {
            get {
                return ResourceManager.GetString("FullForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendered Form.
        /// </summary>
        public static string GenderForm {
            get {
                return ResourceManager.GetString("GenderForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender &amp; Plural.
        /// </summary>
        public static string GnP {
            get {
                return ResourceManager.GetString("GnP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G. &amp; P. Form.
        /// </summary>
        public static string GnPForm {
            get {
                return ResourceManager.GetString("GnPForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        public static string Grammar {
            get {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistics.
        /// </summary>
        public static string Linguistics {
            get {
                return ResourceManager.GetString("Linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Linguistics.
        /// </summary>
        public static string LinguisticsHeader {
            get {
                return ResourceManager.GetString("LinguisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Simple Abbreviation.
        /// </summary>
        public static string ModifySimpleAbbrevTitle {
            get {
                return ResourceManager.GetString("ModifySimpleAbbrevTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- None ---.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Letters.
        /// </summary>
        public static string OneLetters {
            get {
                return ResourceManager.GetString("OneLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Other... ---.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural.
        /// </summary>
        public static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural Form.
        /// </summary>
        public static string PluralForm {
            get {
                return ResourceManager.GetString("PluralForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Postfix {
            get {
                return ResourceManager.GetString("Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run At Start Up.
        /// </summary>
        public static string RunAtStartUp {
            get {
                return ResourceManager.GetString("RunAtStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _See All.
        /// </summary>
        public static string SeeAllHeader {
            get {
                return ResourceManager.GetString("SeeAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Form.
        /// </summary>
        public static string ShortForm {
            get {
                return ResourceManager.GetString("ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Simple Abbrev..
        /// </summary>
        public static string SimpleAbbrevHeader {
            get {
                return ResourceManager.GetString("SimpleAbbrevHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Verb Abbrev..
        /// </summary>
        public static string VerbAbbrevHeader {
            get {
                return ResourceManager.GetString("VerbAbbrevHeader", resourceCulture);
            }
        }
    }
}
