// <auto-generated />
using FasType.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FasType.Migrations.EFSqliteDictionary
{
    [DbContext(typeof(EFSqliteDictionaryContext))]
    partial class EFSqliteDictionaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FasType.Models.Dictionary.BaseDictionaryElement", b =>
                {
                    b.Property<string>("FullForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllForms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Others")
                        .HasColumnType("TEXT");

                    b.HasKey("FullForm");

                    b.ToTable("Dictionary");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseDictionaryElement");
                });

            modelBuilder.Entity("FasType.Models.Dictionary.SimpleDictionaryElement", b =>
                {
                    b.HasBaseType("FasType.Models.Dictionary.BaseDictionaryElement");

                    b.Property<string>("GenderForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderPluralForm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralForm")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SimpleDictionaryElement");
                });
#pragma warning restore 612, 618
        }
    }
}
