// <auto-generated />
using System;
using FasType.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FasType.Migrations
{
    [DbContext(typeof(EFSqliteAbbreviationContext))]
    [Migration("20201203154216_AddOtherShortForms")]
    partial class AddOtherShortForms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FasType.Models.Abbreviations.BaseAbbreviation", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Abbreviations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAbbreviation");
                });

            modelBuilder.Entity("FasType.Models.Abbreviations.SimpleAbbreviation", b =>
                {
                    b.HasBaseType("FasType.Models.Abbreviations.BaseAbbreviation");

                    b.Property<string>("GenderForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderPluralForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortGenderForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortGenderPluralForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortPluralForm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.ToTable("Abbreviations");

                    b.HasDiscriminator().HasValue("SimpleAbbreviation");
                });
#pragma warning restore 612, 618
        }
    }
}
