// <auto-generated />
using System;
using FasType.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FasType.Migrations
{
    [DbContext(typeof(EFSqliteAbbreviationContext))]
    [Migration("20201024180051_BaseAbbreviation")]
    partial class BaseAbbreviation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FasType.Models.Abbreviations.BaseAbbreviation", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullForm")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ShortForm")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.ToTable("Abbreviations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAbbreviation");
                });

            modelBuilder.Entity("FasType.Models.Abbreviations.SimpleAbbreviation", b =>
                {
                    b.HasBaseType("FasType.Models.Abbreviations.BaseAbbreviation");

                    b.ToTable("SimpleAbbreviations");

                    b.HasDiscriminator().HasValue("SimpleAbbreviation");
                });
#pragma warning restore 612, 618
        }
    }
}
